"use client";
import { Download, Printer } from "lucide-react";
import { useData } from "@/components/data-provider";
import { PageHeading } from "@/components/page-heading";
import { Button, Card } from "@/components/ui";
import { calculateMetrics, weeklyReport } from "@/services/metrics";
import { pct, usd } from "@/lib/format";

export default function ReportsPage(){const {data}=useData();const m=calculateMetrics(data);const weeks=weeklyReport(data);const expense=new Map<string,number>();data.transactions.filter(t=>t.type==="expense").forEach(t=>expense.set(t.category,(expense.get(t.category)||0)+t.amount));const top=[...expense].sort((a,b)=>b[1]-a[1]).slice(0,5);
 function csv(){const rows=[["June 2026 Monthly Report"],["Money In",m.income],["Money Out",m.expenses],["Labor Cost",m.labor],["Monthly Profit",m.profit],["Profit Margin",`${m.margin.toFixed(1)}%`],[],["Top Expense Categories"],...top];const blob=new Blob([rows.map(r=>r.join(",")).join("\n")],{type:"text/csv"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="garden-table-june-2026.csv";a.click();URL.revokeObjectURL(a.href)}
 return <div className="space-y-6"><PageHeading title="June monthly report" text="A clean summary you can save, print, or share." action={<div className="flex gap-2"><Button variant="secondary" onClick={()=>window.print()}><Printer size={16}/> Print / PDF</Button><Button onClick={csv}><Download size={16}/> Download CSV</Button></div>}/>
 <Card className="p-6 sm:p-8 print:border-0 print:shadow-none"><div className="flex items-center justify-between border-b pb-6"><div><div className="text-xl font-bold">The Garden Table</div><div className="text-sm text-slate-500">Monthly profit report · June 2026</div></div><div className={`rounded-full px-4 py-2 text-sm font-bold ${m.profit>=0?"bg-emerald-50 text-emerald-700":"bg-rose-50 text-rose-700"}`}>{m.profit>=0?"Profitable month":"Loss this month"}</div></div>
 <div className="grid gap-4 border-b py-7 sm:grid-cols-2 lg:grid-cols-5"><Stat l="Money In" v={usd(m.income)}/><Stat l="Money Out" v={usd(m.expenses)}/><Stat l="Labor Cost" v={usd(m.labor)}/><Stat l="Monthly Profit" v={usd(m.profit)} green/><Stat l="Profit Margin" v={pct(m.margin)}/></div>
 <div className="grid gap-8 py-7 lg:grid-cols-2"><section><h3 className="font-bold">Biggest expenses</h3><div className="mt-4 space-y-3">{top.map(([name,value],i)=><div className="flex items-center gap-3" key={name}><span className="grid size-7 place-items-center rounded-full bg-slate-100 text-xs font-bold">{i+1}</span><span className="flex-1 text-sm">{name}</span><b className="text-sm">{usd(value)}</b></div>)}</div></section><section><h3 className="font-bold">Weekly performance</h3><div className="mt-4 space-y-3">{weeks.filter(w=>w.income).map(w=><div className="flex items-center" key={w.week}><span className="flex-1 text-sm">{w.week}</span><span className="mr-6 text-sm text-slate-500">{usd(w.income)} sales</span><b className="text-sm text-emerald-700">{usd(w.profit)} profit</b></div>)}</div></section></div>
 <div className="grid gap-4 rounded-xl bg-slate-50 p-5 sm:grid-cols-3"><Stat l="Sales goal" v={`${Math.min(100,m.income/data.target.sales*100).toFixed(0)}%`}/><Stat l="Profit goal" v={`${Math.min(100,m.profit/data.target.profit*100).toFixed(0)}%`}/><Stat l="Needs review" v={String(m.needsReview)}/></div></Card></div>}
function Stat({l,v,green}:{l:string;v:string;green?:boolean}){return <div><div className="text-xs font-medium text-slate-500">{l}</div><div className={`mt-1 text-xl font-bold ${green?"text-emerald-700":""}`}>{v}</div></div>}
